In [1]:
%run helper/setup_notebook.ipynb

Successfully connected to universities database.

![erd](../../assets/universities_erd.png)

```js

+--------------+          +-----------------+          +-----------------------+
|   country    |          |  university     |          |     ranking_system    |
+--------------+          +-----------------+          +-----------------------+
| id (PK)      |          | id (PK)         |          | id (PK)               |
| country_name |----------| country_id (FK) |          | system_name           |
+--------------+          | university_name |           +-----------------------+
                           +----------------+

+-----------------------+        +---------------------------+
|     ranking_criteria  |        |       university_year     |
+-----------------------+        +---------------------------+
| id (PK)               |        | university_id (FK)        |
| ranking_system_id (FK)|--------| year                      |
| criteria_name         |        | num_students              |
+-----------------------+        | student_staff_ratio       |
                                 | pct_international_students|
                                 | pct_female_students       |
                                 +---------------------------+

+---------------------------+
|  university_ranking_year  |
+---------------------------+
| university_id (FK)        |
| ranking_criteria_id (FK)  |
| year                      |
| score                     |
+---------------------------+

```

In [9]:
%%sql 

SELECT
u.university_name,
c.country_name,
rc.criteria_name,
ury.year,
ury.score
FROM university u
INNER JOIN country c ON u.country_id = c.id
INNER JOIN university_ranking_year ury ON ury.university_id = u.id
INNER JOIN ranking_criteria rc ON ury.ranking_criteria_id = rc.id
WHERE rc.criteria_name IN (
'Total Times',
'Total Shanghai',
'Total CWUR'
)
AND ury.year = 2010
ORDER BY ury.score DESC;

[('Harvard University', 'United States of America', 'Total Shanghai', 2010, 100),
 ('University of California, Berkeley', 'United States of America', 'Total Shanghai', 2010, 72),
 ('Stanford University', 'United States of America', 'Total Shanghai', 2010, 72),
 ('University of Cambridge', 'United Kingdom', 'Total Shanghai', 2010, 70),
 ('California Institute of Technology', 'United States of America', 'Total Shanghai', 2010, 64),
 ('Princeton University', 'United States of America', 'Total Shanghai', 2010, 61),
 ('Columbia University', 'United States of America', 'Total Shanghai', 2010, 60),
 ('University of Chicago', 'United States of America', 'Total Shanghai', 2010, 57),
 ('University of Oxford', 'United Kingdom', 'Total Shanghai', 2010, 56),
 ('Yale University', 'United States of America', 'Total Shanghai', 2010, 55),
 ('Cornell University', 'United States of America', 'Total Shanghai', 2010, 53),
 ('University of California, Los Angeles', 'United States of America', 'Total Shanghai', 2010, 52),
 ('University of California, San Diego', 'United States of America', 'Total Shanghai', 2010, 50),
 ('University of Pennsylvania', 'United States of America', 'Total Shanghai', 2010, 49),
 ('University of Washington', 'United States of America', 'Total Shanghai', 2010, 49),
 ('University of California, San Francisco', 'United States of America', 'Total Shanghai', 2010, 46),
 ('University College London', 'United Kingdom', 'Total Shanghai', 2010, 44),
 ('Kyoto University', 'Japan', 'Total Shanghai', 2010, 43),
 ('University of Illinois at Urbana-Champaign', 'United States of America', 'Total Shanghai', 2010, 43),
 ('University of Toronto', 'Canada', 'Total Shanghai', 2010, 42),
 ('University of Minnesota, Twin Cities', 'United States of America', 'Total Shanghai', 2010, 41),
 ('Northwestern University', 'United States of America', 'Total Shanghai', 2010, 38),
 ('Washington University in St. Louis', 'United States of America', 'Total Shanghai', 2010, 38),
 ('New York University', 'United States of America', 'Total Shanghai', 2010, 38),
 ('University of California, Santa Barbara', 'United States of America', 'Total Shanghai', 2010, 37),
 ('Rockefeller University', 'United States of America', 'Total Shanghai', 2010, 37),
 ('Duke University', 'United States of America', 'Total Shanghai', 2010, 35),
 ('University of British Columbia', 'Canada', 'Total Shanghai', 2010, 35),
 ('University of Maryland, College Park', 'United States of America', 'Total Shanghai', 2010, 35),
 ('University of Copenhagen', 'Denmark', 'Total Shanghai', 2010, 33),
 ('University of North Carolina at Chapel Hill', 'United States of America', 'Total Shanghai', 2010, 33),
 ('Karolinska Institute', 'Sweden', 'Total Shanghai', 2010, 33),
 ('University of California, Davis', 'United States of America', 'Total Shanghai', 2010, 32),
 ('University of California, Irvine', 'United States of America', 'Total Shanghai', 2010, 32),
 ('University of Southern California', 'United States of America', 'Total Shanghai', 2010, 32),
 ('Utrecht University', 'Netherlands', 'Total Shanghai', 2010, 32),
 ('University of Zurich', 'Switzerland', 'Total Shanghai', 2010, 31),
 ('Vanderbilt University', 'United States of America', 'Total Shanghai', 2010, 31),
 ('Rutgers, the State University of New Jersey', 'United States of America', 'Total Shanghai', 2010, 31),
 ('University of Pittsburgh', 'United States of America', 'Total Shanghai', 2010, 31),
 ('Carnegie Mellon University', 'United States of America', 'Total Shanghai', 2010, 30),
 ('McGill University', 'Canada', 'Total Shanghai', 2010, 30),
 ('University of Melbourne', 'Australia', 'Total Shanghai', 2010, 29),
 ("King's College London", 'United Kingdom', 'Total Shanghai', 2010, 29),
 ('Brown University', 'United States of America', 'Total Shanghai', 2010, 29),
 ('University of Bristol', 'United Kingdom', 'Total Shanghai', 2010, 29),
 ('Uppsala University', 'Sweden', 'Total Shanghai', 2010, 29),
 ('University of Florida', 'United States of America', 'Total Shanghai', 2010, 29),
 ('Leiden University', 'Netherlands', 'Total Shanghai', 2010, 28),
 ('École normale supérieure - Paris', 'France', 'Total Shanghai', 2010, 28),
 ('University of Helsinki', 'Finland', 'Total Shanghai', 2010, 28),
 ('Osaka University', 'Japan', 'Total Shanghai', 2010, 28),
 ('University of Oslo', 'Norway', 'Total Shanghai', 2010, 28),
 ('Boston University', 'United States of America', 'Total Shanghai', 2010, 27),
 ('University of Arizona', 'United States of America', 'Total Shanghai', 2010, 27),
 ('Stockholm University', 'Sweden', 'Total Shanghai', 2010, 26),
 ('Nagoya University', 'Japan', 'Total Shanghai', 2010, 26),
 ('University of Rochester', 'United States of America', 'Total Shanghai', 2010, 26),
 ('University of Utah', 'United States of America', 'Total Shanghai', 2010, 26),
 ('Tohoku University', 'Japan', 'Total Shanghai', 2010, 26),
 ('University of Nottingham', 'United Kingdom', 'Total Shanghai', 2010, 26),
 ('Michigan State University', 'United States of America', 'Total Shanghai', 2010, 26),
 ('University of Basel', 'Switzerland', 'Total Shanghai', 2010, 26),
 ('McMaster University', 'Canada', 'Total Shanghai', 2010, 25),
 ('Ghent University', 'Belgium', 'Total Shanghai', 2010, 25),
 ('University of Sydney', 'Australia', 'Total Shanghai', 2010, 25),
 ('University of Bonn', 'Germany', 'Total Shanghai', 2010, 25),
 ('University of Virginia', 'United States of America', 'Total Shanghai', 2010, 24),
 ('Case Western Reserve University', 'United States of America', 'Total Shanghai', 2010, 24),
 ('Aarhus University', 'Denmark', 'Total Shanghai', 2010, 24),
 ('Rice University', 'United States of America', 'Total Shanghai', 2010, 24),
 ('University of Birmingham', 'United Kingdom', 'Total Shanghai', 2010, 24)]